import type {
  Lead,
  ConversationMessage,
  Campaign,
  QueueItem,
  SendHealthDay,
} from './types';

let counter = 0;
export function uid(prefix = 'id'): string {
  counter += 1;
  return `${prefix}_${counter}_${Date.now().toString(36)}`;
}

export const mockLeads: Lead[] = [
  {
    id: 'lead_001',
    businessName: 'Sunrise Coffee Roasters',
    category: 'Food & Beverage',
    phone: '+1 415-555-0142',
    email: 'owner@sunrisecoffee.co',
    instagram: '@sunrisecoffee',
    facebook: 'SunriseCoffeeRoasters',
    whatsapp: '+1 415-555-0142',
    consentStatus: 'replied',
    entityType: 'lead',
    createdAt: '2026-08-12T10:00:00Z',
    lastContactedAt: '2026-09-01T14:30:00Z',
  },
  {
    id: 'lead_002',
    businessName: 'Iron Peak Fitness Studio',
    category: 'Fitness & Wellness',
    phone: '+1 628-555-0198',
    email: 'hello@ironpeakfit.com',
    instagram: '@ironpeakfit',
    facebook: '',
    whatsapp: '',
    consentStatus: 'none',
    entityType: 'lead',
    createdAt: '2026-08-15T09:00:00Z',
    lastContactedAt: '2026-08-28T11:00:00Z',
  },
  {
    id: 'lead_003',
    businessName: 'Bloom & Co Florist',
    category: 'Retail',
    phone: '+1 510-555-0177',
    email: '',
    instagram: '@bloomcoflorist',
    facebook: 'BloomAndCoFlorist',
    whatsapp: '',
    consentStatus: 'none',
    entityType: 'lead',
    createdAt: '2026-08-20T12:00:00Z',
    lastContactedAt: null,
  },
  {
    id: 'lead_004',
    businessName: 'Apex Plumbing Services',
    category: 'Home Services',
    phone: '+1 408-555-0123',
    email: 'dispatch@apexplumbing.net',
    instagram: '',
    facebook: '',
    whatsapp: '+1 408-555-0123',
    consentStatus: 'opted_out',
    entityType: 'lead',
    createdAt: '2026-08-22T08:00:00Z',
    lastContactedAt: '2026-08-30T09:15:00Z',
  },
  {
    id: 'lead_005',
    businessName: 'Lakeview Dental Group',
    category: 'Healthcare',
    phone: '+1 415-555-0167',
    email: 'frontdesk@lakeviewdental.com',
    instagram: '@lakeviewdental',
    facebook: 'LakeviewDentalGroup',
    whatsapp: '',
    consentStatus: 'replied',
    entityType: 'lead',
    createdAt: '2026-08-25T10:30:00Z',
    lastContactedAt: '2026-09-02T16:00:00Z',
  },
  {
    id: 'client_001',
    businessName: 'Coastal Realty Group',
    category: 'Real Estate',
    phone: '+1 650-555-0189',
    email: 'team@coastalrealty.com',
    instagram: '@coastalrealty',
    facebook: 'CoastalRealtyGroup',
    whatsapp: '+1 650-555-0189',
    consentStatus: 'replied',
    entityType: 'client',
    createdAt: '2026-07-01T10:00:00Z',
    lastContactedAt: '2026-09-05T10:00:00Z',
  },
  {
    id: 'client_002',
    businessName: 'Nori Sushi Bar',
    category: 'Food & Beverage',
    phone: '+1 415-555-0155',
    email: 'manager@norisushi.com',
    instagram: '@norisushibar',
    facebook: 'NoriSushiBar',
    whatsapp: '',
    consentStatus: 'replied',
    entityType: 'client',
    createdAt: '2026-06-20T10:00:00Z',
    lastContactedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'lead_006',
    businessName: 'Pixel Forge Web Studio',
    category: 'Marketing & Design',
    phone: '',
    email: 'studio@pixelforge.io',
    instagram: '@pixelforgeweb',
    facebook: '',
    whatsapp: '',
    consentStatus: 'none',
    entityType: 'lead',
    createdAt: '2026-09-01T08:00:00Z',
    lastContactedAt: null,
  },
  {
    id: 'lead_007',
    businessName: 'Greenleaf Landscaping',
    category: 'Home Services',
    phone: '+1 510-555-0144',
    email: 'info@greenleafland.com',
    instagram: '',
    facebook: 'GreenleafLandscaping',
    whatsapp: '',
    consentStatus: 'none',
    entityType: 'lead',
    createdAt: '2026-09-03T09:00:00Z',
    lastContactedAt: null,
  },
  {
    id: 'lead_008',
    businessName: 'Unknown Vendor',
    category: 'Misc',
    phone: '',
    email: '',
    instagram: '',
    facebook: '',
    whatsapp: '',
    consentStatus: 'none',
    entityType: 'lead',
    createdAt: '2026-09-05T09:00:00Z',
    lastContactedAt: null,
  },
];

export const mockConversations: ConversationMessage[] = [
  {
    id: 'msg_001',
    leadId: 'lead_001',
    channel: 'email',
    direction: 'outbound',
    text: "Hi there — I noticed Sunrise Coffee recently expanded to a second location. Congratulations! I help local cafés grow their online orders by 30% with a simple setup. Would you be open to a quick chat this week?",
    timestamp: '2026-08-28T14:30:00Z',
    status: 'sent',
  },
  {
    id: 'msg_002',
    leadId: 'lead_001',
    channel: 'email',
    direction: 'inbound',
    text: "Thanks for reaching out! Yes, we're interested. Can you send more details about pricing?",
    timestamp: '2026-09-01T14:00:00Z',
    status: 'delivered',
  },
  {
    id: 'msg_003',
    leadId: 'lead_001',
    channel: 'email',
    direction: 'outbound',
    text: "Absolutely — I'll send over a one-pager with our packages. Talk soon!",
    timestamp: '2026-09-01T14:30:00Z',
    status: 'sent',
  },
  {
    id: 'msg_004',
    leadId: 'lead_005',
    channel: 'instagram',
    direction: 'outbound',
    text: "Hi Lakeview Dental! We help dental practices fill gaps in their appointment calendar with automated reminders. Want to learn more?",
    timestamp: '2026-09-02T16:00:00Z',
    status: 'draft',
  },
  {
    id: 'msg_005',
    leadId: 'client_001',
    channel: 'whatsapp',
    direction: 'outbound',
    text: "Hi Coastal Realty team — your monthly performance report is ready. Want me to walk through it on a call?",
    timestamp: '2026-09-05T10:00:00Z',
    status: 'sent',
  },
  {
    id: 'msg_006',
    leadId: 'client_001',
    channel: 'whatsapp',
    direction: 'inbound',
    text: "Yes, let's do Thursday at 2pm.",
    timestamp: '2026-09-05T11:30:00Z',
    status: 'delivered',
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp_001',
    name: 'Q3 Local Business Outreach',
    targetCategory: 'all',
    targetChannel: 'email',
    createdAt: '2026-08-20T10:00:00Z',
    steps: [
      {
        id: 'step_001',
        name: 'Intro Email',
        channel: 'email',
        delayDays: 0,
        body: "Hi {businessName}, I help {category} businesses in the Bay Area grow their online presence. I'd love to share some ideas — are you open to a 15-minute call this week?",
      },
      {
        id: 'step_002',
        name: 'Follow-up Email',
        channel: 'email',
        delayDays: 4,
        body: "Hi {businessName}, just floating this back to the top of your inbox. Happy to share a quick case study from a similar business if you're curious.",
      },
      {
        id: 'step_003',
        name: 'Final Nudge',
        channel: 'email',
        delayDays: 10,
        body: "Hi {businessName}, I'll stop reaching out after this one. If the timing isn't right, no worries — just reply 'later' and I'll check back in Q4.",
      },
    ],
  },
  {
    id: 'camp_002',
    name: 'Instagram Nurture — Fitness Studios',
    targetCategory: 'Fitness & Wellness',
    targetChannel: 'instagram',
    createdAt: '2026-08-25T10:00:00Z',
    steps: [
      {
        id: 'step_004',
        name: 'Instagram DM',
        channel: 'instagram',
        delayDays: 0,
        body: "Hey {businessName}! Love your studio content. We work with gyms to automate lead follow-ups so you never lose a prospect. Mind if I share a quick idea?",
      },
      {
        id: 'step_005',
        name: 'WhatsApp Follow-up',
        channel: 'whatsapp',
        delayDays: 5,
        body: "Hi {businessName}, it's [your name] from Instagram. I put together a short video showing how we'd automate your lead replies. Want me to send it here?",
      },
    ],
  },
];

export const mockQueue: QueueItem[] = [
  {
    id: 'q_001',
    leadId: 'lead_005',
    leadName: 'Lakeview Dental Group',
    channel: 'instagram',
    campaignName: 'Instagram Nurture — Fitness Studios',
    stepName: 'Instagram DM',
    messagePreview: "Hey Lakeview Dental! We help dental practices fill gaps in their calendar with automated reminders...",
    status: 'draft',
    createdAt: '2026-09-07T10:00:00Z',
  },
  {
    id: 'q_002',
    leadId: 'lead_003',
    leadName: 'Bloom & Co Florist',
    channel: 'instagram',
    campaignName: 'Q3 Local Business Outreach',
    stepName: 'Instagram DM',
    messagePreview: "Hey Bloom & Co! Love your floral arrangements. We help florists get more online orders with a simple setup...",
    status: 'draft',
    createdAt: '2026-09-07T11:00:00Z',
  },
  {
    id: 'q_003',
    leadId: 'lead_006',
    leadName: 'Pixel Forge Web Studio',
    channel: 'instagram',
    campaignName: 'Instagram Nurture — Fitness Studios',
    stepName: 'Instagram DM',
    messagePreview: "Hey Pixel Forge! Your portfolio is impressive. We help studios like yours automate client onboarding...",
    status: 'draft',
    createdAt: '2026-09-07T12:00:00Z',
  },
  {
    id: 'q_004',
    leadId: 'lead_007',
    leadName: 'Greenleaf Landscaping',
    channel: 'instagram',
    campaignName: 'Q3 Local Business Outreach',
    stepName: 'Instagram DM',
    messagePreview: "Hey Greenleaf! Your landscaping work is beautiful. We help local services get more quotes requests online...",
    status: 'draft',
    createdAt: '2026-09-07T13:00:00Z',
  },
];

export const mockSendHealth: SendHealthDay[] = [
  { date: 'Sep 2', sent: 142, bounced: 3, drafted: 8 },
  { date: 'Sep 3', sent: 98, bounced: 1, drafted: 5 },
  { date: 'Sep 4', sent: 187, bounced: 7, drafted: 12 },
  { date: 'Sep 5', sent: 203, bounced: 2, drafted: 9 },
  { date: 'Sep 6', sent: 76, bounced: 0, drafted: 3 },
  { date: 'Sep 7', sent: 154, bounced: 5, drafted: 11 },
  { date: 'Sep 8', sent: 121, bounced: 4, drafted: 7 },
];
